input('Nama                 : ')
input('NIM                  : ')
input('Kelas Pararel        : ')
input('tempat tanggal lahir : ')
input('alamat               : ')
input('hobby                : ')
input('no.hp                : ')